# ate2vec.py
# Copyright (c) 2025 Juneth Viktor Ellon Moreno
# All rights reserved
import os
import re
from datetime import datetime
import metadata

author = metadata.author
sub_script_ver = metadata.script_ver

# -------------------- Vector Parsing --------------------

def sanitize_vector(vec_line):
    allowed_drive = {"1","0","Z"}
    allowed_strobe = {"L","H","X"}
    sanitized = ""
    for ch in vec_line.upper():
        if ch in allowed_drive or ch in allowed_strobe:
            sanitized += ch
        else:
            sanitized += "X"
    return sanitized

def parse_j750_atp_vectors(atp_file):
    """Extract vector bitstrings from J750 ATP file.
    Stop at 'halt', but include the first vector after halt."""
    vectors = []
    include_next_after_halt = False

    with open(atp_file, "r") as f:
        for line in f:
            line = line.strip()
            if include_next_after_halt:
                # Capture only the first line after halt
                if line.startswith("> WFT"):
                    m = re.search(r"> WFT\s+([01XxLHZlhz]+);", line)
                    if m:
                        vec = sanitize_vector(m.group(1))
                        comment_match = re.search(r";\s*//(.*)$", line)
                        comment = comment_match.group(1).strip() if comment_match else None
                        vectors.append((vec, comment))
                break  # Stop reading after the first line after halt

            if line.lower() == "halt":
                include_next_after_halt = True
                continue

            if line.startswith("> WFT"):
                m = re.search(r"> WFT\s+([01XxLHZlhz]+);", line)
                if m:
                    vec = sanitize_vector(m.group(1))
                    comment_match = re.search(r";\s*//(.*)$", line)
                    comment = comment_match.group(1).strip() if comment_match else None
                    vectors.append((vec, comment))

    return vectors


def parse_chroma_pat_vectors(pat_file):
    """Extract vector bitstrings from Chroma PAT file."""
    vectors = []
    with open(pat_file, "r") as f:
        for line in f:
            line = line.strip()
            m = re.search(r"\*([01XxLHZlhz]+)\*", line)
            if m:
                vec = sanitize_vector(m.group(1))
                # Comment handling if present
                comment_match = re.search(r";\s*//(.*)$", line)
                comment = comment_match.group(1).strip() if comment_match else None
                vectors.append((vec, comment))
    return vectors

# -------------------- Pin Extraction --------------------

def parse_j750_pins(atp_file):
    """Extract pin names from J750 ATP $tset line."""
    pins = []
    with open(atp_file, "r") as f:
        for line in f:
            line = line.strip()
            if "$tset" in line:
                m = re.search(r"\(\s*\$tset\s*,(.*)\)", line)
                if m:
                    pin_list = m.group(1).split(',')
                    pins = [p.strip() for p in pin_list if p.strip()]
                    break
    return pins

def parse_chroma_pins(pat_file):
    """Extract pin names from Chroma PAT HEADER section."""
    pins = []
    with open(pat_file, "r") as f:
        lines = f.readlines()
        for i, line in enumerate(lines):
            if "HEADER" in line:
                if i + 1 < len(lines):
                    next_line = lines[i+1].strip().rstrip(';')
                    pins = [p.strip() for p in next_line.split(',') if p.strip()]
                    break
    return pins

# -------------------- File Generation --------------------

# -------------------- File Generation --------------------

def generate_vec_file(vectors, vec_file, ate_file, date):
    with open(vec_file, "w") as f:
        f.write("########################################################\n")
        f.write(f"# Generated by VektorConverter: ate2vec v{sub_script_ver}\n")
        f.write(f"# ATE File : {ate_file}\n")
        f.write(f"# Date     : {date}\n")
        f.write("#\n")
        f.write("########################################################\n")

        # Remove last vector only if it is a dummy (all X)
        if vectors and all(c == "X" for c in vectors[-1][0]):
            print("Removing extra dummy vector at the end")
            vectors = vectors[:-1]

        # Write vectors with line numbers starting from 0
        for idx, (vec, comment) in enumerate(vectors):
            if comment:
                f.write(f"#{comment}\n")
            f.write(f"{idx} {vec}\n")  # Add line number before vector

    print(f"VEC file written: {vec_file}")



def generate_cmf_file(pin_names, cmf_file):
    """Write CMF file with pins in reverse order."""
    with open(cmf_file, "w") as f:
        for idx, pin in enumerate(reversed(pin_names)):
            f.write(f"{pin},{idx},T2,USE\n")
    print(f"CMF file written: {cmf_file}")

# -------------------- Main --------------------

def main():
    input_file = input("Enter .atp (J750) or .pat (Chroma) file: ").strip()
    input_file = os.path.abspath(input_file)
    ext = os.path.splitext(input_file)[1].lower()

    # Store ATE file and date for VEC header
    ate_file = os.path.basename(input_file)
    date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if ext == ".atp":
        vectors = parse_j750_atp_vectors(input_file)
        pins = parse_j750_pins(input_file)
    elif ext == ".pat":
        vectors = parse_chroma_pat_vectors(input_file)
        pins = parse_chroma_pins(input_file)
    else:
        print("ERROR: Unsupported file type. Use .atp or .pat")
        return

    if not vectors:
        print("ERROR: No vectors found in input file.")
        return

    if not pins:
        # Fallback: generate generic pin names
        pins = [f"PIN{i}" for i in range(len(vectors[0][0]))]
        print("WARNING: No pins found, using generic PIN0..PINn")

    base_name = os.path.splitext(os.path.basename(input_file))[0]
    vec_file = os.path.join(os.path.dirname(input_file), base_name + ".vec")
    cmf_file = os.path.join(os.path.dirname(input_file), base_name + ".cmf")

    # Pass ate_file and date to include in header
    generate_vec_file(vectors, vec_file, ate_file, date)
    generate_cmf_file(pins, cmf_file)

if __name__ == "__main__":
    print("#############################################################")
    print("#\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t#")
    print("#\t\t\t\t\t\tVektorConverter\t\t\t\t\t\t#")
    print(f"#\t\t\t\t\t\tate2vec v{sub_script_ver}\t\t\t\t\t\t#")
    print(f"#\t\t\t\t\tby: {author}\t\t\t#")
    print("##############################################################")
    main()
