# stil2vec.py
# Copyright (c) 2025 Juneth Viktor Ellon Moreno
# All rights reserved
import os
import re
from datetime import datetime
import metadata

author = metadata.author
sub_script_ver = metadata.script_ver

# Map STIL characters to allowed .vec characters
VALUE_MAP = {
    '1': '1',
    '0': '0',
    'L': '0', 'l': '0',
    'H': '1', 'h': '1',
    'X': 'X', 'x': 'X',
    'Z': 'X', 'z': 'X',
    'N': 'X',
    'U': 'X',
    'D': 'X',
    'T': 'X'
}

# ---------------- CMF ----------------
def generate_cmf_from_pins(pin_list, cmf_file):
    """Write CMF file with pins in reverse order, extract name inside quotes"""
    with open(cmf_file, "w") as f:
        for idx, pin in enumerate(reversed(pin_list)):
            m = re.search(r'"([^"]+)"', pin)
            pin_name = m.group(1) if m else pin
            f.write(f"{pin_name},{idx},T2,USE\n")
    return cmf_file

# ---------------- STIL Parsing ----------------
def parse_stil_period(stil_file):
    """Extract period from STIL Timing block"""
    period = None
    with open(stil_file, "r") as f:
        content = f.read()
        match = re.search(
            r'Timing\s*\{.*?WaveformTable\s*"[^"]+"\s*\{.*?Period\s+[\'"]([\d\.]+)ns[\'"]',
            content,
            re.DOTALL | re.IGNORECASE
        )
        if match:
            period = match.group(1)
    return period

def parse_stil_pins(stil_file):
    """Extract all signal names from STIL Signals block"""
    with open(stil_file, "r") as f:
        content = f.read()
        signals_match = re.search(r"Signals\s*\{(.*?)\}", content, re.DOTALL | re.IGNORECASE)
        if signals_match:
            signals_block = signals_match.group(1)
            return re.findall(r'"([^"]+)"', signals_block)
    return []

def sanitize_value(val):
    """Ensure vector values are only L,H,0,1,X"""
    return VALUE_MAP.get(val, 'X')

def parse_stil_vectors(stil_file, pins):
    """Return vector lines for STIL file based on pin order, mapping all values to allowed characters"""
    state = {p: 'X' for p in pins}  # all pins default to X
    vectors = []

    with open(stil_file, "r") as f:
        content = f.read()
        # Find all V { ... } blocks
        v_blocks = re.findall(r'V\s*\{(.*?)\}', content, re.DOTALL | re.IGNORECASE)
        for block in v_blocks:
            # Update only pins listed in this block
            for name, val in re.findall(r'"([^"]+)"\s*=\s*([^\s;]+);', block):
                if name in state:
                    state[name] = sanitize_value(val)
            # Build vector line in pin order
            vec_line = "".join(state[p] for p in pins)
            vectors.append(vec_line)
    return vectors

# ---------------- Callable Function ----------------
def convert_stil_to_vec(stil_file_path):
    """Convert STIL file to .vec and .cmf; returns (vec_file, cmf_file)"""
    stil_file = os.path.abspath(stil_file_path)
    base_name = os.path.splitext(os.path.basename(stil_file))[0]

    period = parse_stil_period(stil_file)
    pins = parse_stil_pins(stil_file)
    vectors = parse_stil_vectors(stil_file, pins)

    if not pins and vectors:
        pins = [f"PIN{i}" for i in range(len(vectors[0]))]

    cmf_file = os.path.join(os.path.dirname(stil_file), base_name + ".cmf")
    generate_cmf_from_pins(pins, cmf_file)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    vec_file = os.path.join(os.path.dirname(stil_file), base_name + ".vec")
    with open(vec_file, "w") as f:
        f.write("########################################################\n")
        f.write(f"# Generated by VektorConverter: stil2vec v{sub_script_ver}\n")
        f.write(f"# STIL File    : {stil_file}\n")
        if period:
            f.write(f"# Period       : {period} ns\n")
        f.write(f"# Timestamp    : {timestamp}\n")
        f.write("########################################################\n")
        for idx, vec in enumerate(vectors):
            f.write(f"{idx} {vec}\n")

    return vec_file, cmf_file
